### ISSUE TITLE
Pivoted charts fail on Snowflake: __grp_rn ROW_NUMBER() is missing ORDER BY (regression in 0.3226.1)

### ISSUE THREAD

**Issue by lpillmann** [lightdash/lightdash#24638]
### Description

_Note: investigation and bug report assisted by Claude Code_

---

After upgrading from 0.2761.4 to 0.3226.1, every chart with a `pivotConfig` started failing on a Snowflake warehouse with:

    SQL compilation error: Window function type [ROW_NUMBER] requires ORDER BY in window specification.

The offending fragment is in Lightdash's pivot wrapper (the final-stage `total_columns` subquery):

```sql
ROW_NUMBER() OVER (
  PARTITION BY "dim_institutions_institution_type"
) AS "__grp_rn"
```

That ROW_NUMBER() has a PARTITION BY but no ORDER BY — Snowflake refuses it, where some other engines tolerate it. The non-pivot version of the same query (no pivotConfig) works fine; only the pivot wrapper introduces this window.

0.3226.1's release notes describe a pivot change — "pivot: collapse final-stage total_columns into a single pass" (https://github.com/lightdash/lightdash/releases/tag/0.3226.1) — which is consistent with two windows being collapsed into one and the ORDER BY dropped. Pinning to 0.3226.0 (which has no pivot-related changes) resolves the error.

Suggested fix: add a deterministic ORDER BY to the __grp_rn window (e.g. ORDER BY 1 or ORDER BY (SELECT NULL)). The window's value isn't order-dependent — it's only used as a flag (WHEN __grp_rn = 1 THEN 1 ELSE 0) — so any deterministic ORDER BY satisfies Snowflake without changing results.

Full generated SQL (failing on 0.3226.1)

```sql
WITH
  original_query AS (
    SELECT
      DATE_TRUNC('MONTH', "fct_invoice_lines_combined".invoice_line_date)
        AS "fct_invoice_lines_combined_invoice_line_date_month",
      "dim_institutions".institution_type AS "dim_institutions_institution_type",
      SUM(CASE WHEN "fct_invoice_lines_combined".is_meal = true
               THEN "fct_invoice_lines_combined".quantity END)
        AS "fct_invoice_lines_combined_total_meal_count"
    FROM PROD_ANALYTICS.marts.fct_invoice_lines_combined AS "fct_invoice_lines_combined"
    LEFT OUTER JOIN PROD_ANALYTICS.marts.dim_institutions AS "dim_institutions"
      ON "fct_invoice_lines_combined".institution_sk = "dim_institutions".institution_sk
    WHERE DATE_TRUNC('MONTH', "fct_invoice_lines_combined".invoice_line_date) >= '2021-01-01'
    GROUP BY 1, 2
    ORDER BY "fct_invoice_lines_combined_invoice_line_date_month"
  ),
  group_by_query AS (
    SELECT
      "dim_institutions_institution_type",
      "fct_invoice_lines_combined_invoice_line_date_month",
      ANY_VALUE("fct_invoice_lines_combined_total_meal_count")
        AS "fct_invoice_lines_combined_total_meal_count_any"
    FROM original_query
    GROUP BY "dim_institutions_institution_type", "fct_invoice_lines_combined_invoice_line_date_month"
  ),
  pivot_query AS (
    SELECT
      g.*,
      DENSE_RANK() OVER (ORDER BY g."fct_invoice_lines_combined_invoice_line_date_month" ASC) AS "row_index",
      DENSE_RANK() OVER (ORDER BY g."dim_institutions_institution_type" ASC) AS "column_index"
    FROM group_by_query g
  ),
  filtered_rows AS (SELECT * FROM pivot_query WHERE "row_index" <= 500)
SELECT
  "fct_invoice_lines_combined_invoice_line_date_month",
  "dim_institutions_institution_type",
  "fct_invoice_lines_combined_total_meal_count_any",
  "row_index", "column_index", total_columns
FROM (
  SELECT
    p.*,
    SUM(CASE WHEN p."__grp_rn" = 1 THEN 1 ELSE 0 END) OVER () AS total_columns
  FROM (
    SELECT
      f.*,
      ROW_NUMBER() OVER (PARTITION BY "dim_institutions_institution_type") AS "__grp_rn"  -- ← missing ORDER BY
    FROM filtered_rows f
  ) p
) pivoted
WHERE "column_index" <= 200
ORDER BY "row_index", "column_index"
```

Blast radius observed on our instance: 19 of 34 charts (every one using pivotConfig).

### Steps to Reproduce the Bug or Issue

1. Self-host Lightdash 0.3226.1 against a Snowflake warehouse.
2. Build any chart with at least one dimension, one metric, and a categorical pivot column. Minimal chart spec:

```
metricQuery:
  dimensions: [some_date_dimension, some_categorical_dimension]
  metrics:   [some_metric]
pivotConfig:
  columns:   [some_categorical_dimension]
```
 
5. Run the query → Snowflake returns: SQL compilation error: Window function type [ROW_NUMBER] requires ORDER BY in window specification.
6. Remove pivotConfig → query works.
7. Pin back to 0.3226.0 (no pivot changes) → query works.

### version

0.3226.1

### Cloud or self-hosting

self-hosting
